[flint]
version = 1

[common.indent]
indent_style = "spaces"                             # Options: "spaces", "tabs"
indent_size = 4
switch_case = 5
function_declaration = { body = 2, parameters = 3 }

[common]
# Basic style settings

max_line_length = 100
quote_style = "double"
require_semicolons = true

# Naming conventions
variable_case = "camelCase"
function_case = "camelCase"
class_case = "PascalCase"
constant_case = "UPPER_CASE"


[rules.eslint]

[config.eslint]
root = "./flint-tests/src/js"
ignore = ["node_modules", "coverage"]

[tests.jest]
testEnvironment = "node"
testMatch = ["**/tests/**/*.test.js"]
collectCoverage = true

[ci]

[report]

# [ci.github-actions]
# branches = ["main"]
# node_version = ["16.x"]

# [report.json]
# outputPath = "./lint-report.json"
